#!/usr/bin/env bash
#configures an Nginx server to listen on port 80

apt-get update -y
apt-get install -y nginx
sudo service nginx enable
sudo service nginx start

sudo ln -sf /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo service nginx restart 
