#!/usr/bin/env bash
#configures an Nginx server to listen on port 80

rm /etc/nginx/sites-enabled/default
in -s  /etc/nginx/site-available/default/etc/nginx/sites-enabled/default
service nginx restart
