#!/usr/bin/env bash
#configures an nginx server to listen to poert 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)”
