#!/usr/bin/env bash
#configures an nginx server to listen to poert 80

in -sf /etc/nginx/sites-availaible/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
