#!/usr/bin/env bash
#Run Nginx

# Modify the nginx configuration to use the nginx user
sudo sed -i 's/user www-data/user nginx' /etc/nginx/nginx.conf

# Change the port number in the sites-available default configuration
sudo sed -i 's/80/800/g' /etc/nginx/sites-available/default

# Set proper permissions for the nginx configuration file
sudo chmod 644 /etc/nginx/nginx.conf

pkill apache2

# Restart the nginx service as root
sudo -u nginx service nginx restart
